services:
    goutte_client:
        class: Goutte\Client
    kickass_parser:
        class: AppBundle\Parser\KickAssParser
        arguments: ["@goutte_client", "@doctrine"]
    imdb_parser:
        class: AppBundle\Parser\ImdbParser
        arguments: ["@goutte_client", "@doctrine"]
    parse_kickass_command:
        class: AppBundle\Command\ParseKickAssCommand
        arguments: ["@doctrine", "@validator", "@kickass_parser", "@imdb_parser", "@logger"]
        tags:
            -  { name: console.command }