<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Tools\Pagination\Paginator;


/**
 * MovieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MovieRepository extends EntityRepository
{

    public function getMovies()
    {
        $dql = "SELECT g,m,t
                FROM AppBundle:Movie m
                JOIN m.torrents t
                LEFT JOIN m.genres g
                ORDER BY m.imdbRating DESC";
        $query = $this->getEntityManager()->createQuery($dql);
        $query->setMaxResults(20);
        $paginator = new Paginator($query);
        return $paginator;
    }

}
